package ru.roseurobank.main.portal01;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.15
 * 2015-04-06T13:11:13.308+04:00
 * Generated source version: 2.7.15
 * 
 */
@WebServiceClient(name = "bitrix.webservice.exchangerate", 
                  wsdlLocation = "portal.wsdl",
                  targetNamespace = "http://portal01.main.roseurobank.ru/") 
public class BitrixWebserviceExchangerate extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://portal01.main.roseurobank.ru/", "bitrix.webservice.exchangerate");
    public final static QName CExchangeRateSoap = new QName("http://portal01.main.roseurobank.ru/", "CExchangeRateSoap");
    static {
        URL url = BitrixWebserviceExchangerate.class.getResource("portal.wsdl");
        if (url == null) {
            url = BitrixWebserviceExchangerate.class.getClassLoader().getResource("portal.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(BitrixWebserviceExchangerate.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "portal.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public BitrixWebserviceExchangerate(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BitrixWebserviceExchangerate(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BitrixWebserviceExchangerate() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
/*    public BitrixWebserviceExchangerate(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BitrixWebserviceExchangerate(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BitrixWebserviceExchangerate(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }*/

    /**
     *
     * @return
     *     returns CExchangeRateInterface
     */
    @WebEndpoint(name = "CExchangeRateSoap")
    public CExchangeRateInterface getCExchangeRateSoap() {
        return super.getPort(CExchangeRateSoap, CExchangeRateInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CExchangeRateInterface
     */
    @WebEndpoint(name = "CExchangeRateSoap")
    public CExchangeRateInterface getCExchangeRateSoap(WebServiceFeature... features) {
        return super.getPort(CExchangeRateSoap, CExchangeRateInterface.class, features);
    }

}
