
package ru.roseurobank.main.portal01;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.math.BigInteger;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.apache.cxf.Bus;
import org.apache.cxf.BusFactory;
import org.apache.cxf.endpoint.Client;
import org.apache.cxf.frontend.ClientProxy;
import org.apache.cxf.transport.http.HTTPConduit;
import org.apache.cxf.transport.http.asyncclient.AsyncHTTPConduit;
import org.apache.cxf.transports.http.configuration.HTTPClientPolicy;
import org.apache.http.auth.Credentials;
import org.apache.http.auth.NTCredentials;

/**
 * This class was generated by Apache CXF 2.7.15
 * 2015-04-06T13:11:13.244+04:00
 * Generated source version: 2.7.15
 * 
 */
public final class CExchangeRateInterface_CExchangeRateSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://portal01.main.roseurobank.ru/", "bitrix.webservice.exchangerate");

    private CExchangeRateInterface_CExchangeRateSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BitrixWebserviceExchangerate.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
         Rate r= new Rate();
        r.setCODE(BigInteger.valueOf(4));
        r.setDATE("26.02.2015 17:00:00");
        r.setCODEIN("USD");
        r.setBUYVALUE(Float.valueOf("0.25"));
        r.setSELLVALUE(Float.valueOf("0.25"));
        
                
        ru.roseurobank.main.portal01.ArRate ar= new ArRate();
        ar.getArRateEl().add(r);
        
        BitrixWebserviceExchangerate ss = new BitrixWebserviceExchangerate(wsdlURL, SERVICE_NAME);
        CExchangeRateInterface port = ss.getCExchangeRateSoap();  
        
        //Turn off chunking so that NTLM can occur
Client client = ClientProxy.getClient(port);
HTTPConduit http = (HTTPConduit) client.getConduit();
HTTPClientPolicy httpClientPolicy = new HTTPClientPolicy();
httpClientPolicy.setConnectionTimeout(36000);
httpClientPolicy.setAllowChunking(false);
httpClientPolicy.setAutoRedirect(true);
http.setClient(httpClientPolicy);

Bus bus = BusFactory.getDefaultBus();
// insist on the async connector to use PATCH.
bus.setProperty(AsyncHTTPConduit.USE_ASYNC, Boolean.TRUE);

bus.setProperty("use.async.http.conduit", Boolean.TRUE);
 ((BindingProvider)port).getRequestContext().put("use.async.http.conduit", Boolean.TRUE);
Credentials creds = new NTCredentials("qqq", "www", "", "MAIN");
bus.setProperty(Credentials.class.getName(), creds);

((BindingProvider)port).getRequestContext().put(Credentials.class.getName(), creds);
        
        {
        System.out.println("Invoking setRates...");
        //ru.roseurobank.main.portal01.ArRate _setRates_arRate = null;
        ru.roseurobank.main.portal01.CResponse _setRates__return = port.setRates(ar);
        System.out.println("setRates.result=" + _setRates__return);


        }

        System.exit(0);
    }

}
