package ru.roseurobank.main.portal01;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.15
 * 2015-04-06T13:11:13.300+04:00
 * Generated source version: 2.7.15
 * 
 */
@WebService(targetNamespace = "http://portal01.main.roseurobank.ru/", name = "CExchangeRateInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface CExchangeRateInterface {

    @WebResult(name = "out", targetNamespace = "http://portal01.main.roseurobank.ru/")
    @RequestWrapper(localName = "setRates", targetNamespace = "http://portal01.main.roseurobank.ru/", className = "ru.roseurobank.main.portal01.SetRates")
    @WebMethod(action = "http://portal01.main.roseurobank.ru/setRates")
    @ResponseWrapper(localName = "setRatesResponse", targetNamespace = "http://portal01.main.roseurobank.ru/", className = "ru.roseurobank.main.portal01.SetRatesResponse")
    public ru.roseurobank.main.portal01.CResponse setRates(
        @WebParam(name = "arRate", targetNamespace = "http://portal01.main.roseurobank.ru/")
        ru.roseurobank.main.portal01.ArRate arRate
    );
}
